FROM php:8.2-apache

RUN apt-get update && \
    apt-get install -y tesseract-ocr imagemagick ghostscript libmagickwand-dev && \
    pecl install imagick && \
    docker-php-ext-enable imagick

# Allow PDF conversion in ImageMagick
COPY imagemagick-policy.xml /etc/ImageMagick-6/policy.xml

COPY ./public/ /var/www/html/
