FROM php:8.2-apache

RUN apt-get update && \
    apt-get install -y imagemagick ghostscript libmagickwand-dev tesseract-ocr && \
    pecl install imagick && \
    docker-php-ext-enable imagick

COPY ./public/ /var/www/html/
