FROM php:8.2-apache

RUN apt-get update && \
    apt-get install -y tesseract-ocr imagemagick ghostscript libmagickwand-dev && \
    pecl install imagick && \
    docker-php-ext-enable imagick

COPY ./public/ /var/www/html/
