FROM php:8.2-apache

# Install required packages
RUN apt-get update && \
    apt-get install -y cron php-cli tesseract-ocr imagemagick ghostscript libmagickwand-dev && \
    pecl install imagick && \
    docker-php-ext-enable imagick

# Copy app files
COPY ./public/ /var/www/html/
COPY crontab /etc/cron.d/ocr-cron

# Set permissions and register cron job
RUN chmod 0644 /etc/cron.d/ocr-cron && \
    crontab /etc/cron.d/ocr-cron

# Start Apache and cron together
CMD cron && apache2-foreground